BULLET_WIDTH = 2
BULLET_HEIGHT = 2


PLAYER_SPEED = 5
PLAYER_WIDTH = 20
PLAYER_HEIGHT = 20
PLAYER_HEALTH = 100

PLAYER_BULLET_CHECK_COLLISION_SPEED = 10
PLAYER_BULLET_SPEED = 13

PISTOL_DAMAGE = 1
PISTOL_SHOOT_COOLDOWN = 20
PISTOL_RELOAD_COOLDOWN = 120
PISTOL_CAPACITY = 10
